spring:
  application:
    name: zuul-edge-service
  boot:
    admin:
      client:
        url: http://localhost:8080
server:
  port: 8084
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    product-service:
      path: /service/products/**
      serviceId: product-service
      strip-prefix: false
    order-service:
      path: /service/orders/**
      serviceId: order-service
      strip-prefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka

logging:
  level:
    root: INFO
    com.netflix.*: INFO
    org.springframework.cloud.*: INFO