spring:
  application:
    name: zuul-edge-service
server:
  port: 8084
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    product-service:
      path: /service/products/**
      serviceId: product-service
      strip-prefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka

logging:
  level:
    com:
      netflix:
        eureka: debug
        discovery: debug
    org:
      springframework:
        cloud:
          netflix: trace