version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: order-service
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  order-service:
    image: orderservice:latest
    ports:
      - 8088:8088
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db